### PR TITLE
Awesome Book JavaScript classes

### PR DESCRIPTION
**Pull request by Shabiblac**
In this branch, my partner and I :

- Created class methods to add and remove books.
- Added CSS styles to the application
Screenshot (12)

### CODE REVIEW

**Review by LionRouge1 — COMMENTED** [review]
Hi @Shabiblac, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is supposed to be a pair-programming activity but you are the only one who contributed to the project. Kindly work with your partner to submit this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by Shabiblac** [comment]
Hi [LionRouge1](https://github.com/LionRouge1)
I dont have a partner again he just left the program and have not been issued a new partner

**Comment by Shabiblac** [comment]
Hi,
I don't have a coding partner at the moment he left this morning and have
not been given a new partner.

**Comment by LionRouge1** [comment]
Sorry @Shabiblac for the delay. Please write to student success about your partner. So they can allow you to work alone

**Review by Munsa1 — APPROVED** [review]
Hi @Shabiblac, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
All Relevant Methods Implemented Inside A Class :heavy_check_mark: 
App Works As Expected :heavy_check_mark: 
Descriptive Branch Name :heavy_check_mark: 
Good Commit Messages :heavy_check_mark:

## Optional suggestions
- [ ] You could deploy your app using GitHub pages so as to give users a `Live Demo`
- [ ] 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
